### ISSUE TITLE
install dependencies fail

### ISSUE THREAD

**Issue by ChopperLee2011** [Wiredcraft/bunyan-logger#8]
seems the same issue with #5  now we need to support node v8,v9 ...
but install dependencies lib: `syslog-bunyan-logger` faild on my local machine,
part of error message:
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
```

 here are some env value.
```
 ~/Program/node/bunyan-logger  node -v                                                                         1 ↵   
v8.11.3
 ~/Program/node/bunyan-logger  npm -v                                                                            ✔   
5.6.0
 ~/Program/node/bunyan-logger  uname -a                                                                          ✔   
Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```
and its homepage is 404.
so I suggest to change back to [node-bunyan-syslog](https://github.com/joyent/node-bunyan-syslog), which is better maintained, and already fixed some node version problem.

**Comment by ChopperLee2011** [comment]
upgrade to python3 can fix install `syslog-bunyan-logger`.
